#!/bin/bash
set -e -o pipefail

source "$(dirname "$0")/set_k8s_context"

echo "*******************************************************************"
echo "Using EKS_TOKEN env var as a token."
k8s_token=$(echo $EKS_TOKEN | base64 -d)

echo "Using EKS_CLUSTER_CERT env var."
cluster_cert=$EKS_CLUSTER_CERT

echo "Using EKS_CLUSTER_NAME env var."
cluster_name=$EKS_CLUSTER_NAME
echo "*******************************************************************"
echo

k8s_namespace=formbuilder-repos

echo "*******************************************************************"
environment_name=$ENVIRONMENT_NAME
echo "environment_name is ${environment_name}"
echo "*******************************************************************"
echo

echo "*******************************************************************"
branch_name=$CIRCLE_BRANCH
echo "branch_name is ${branch_name}"
echo "*******************************************************************"
echo

set_context "circleci" "${k8s_namespace}" "${k8s_token}" "${cluster_cert}" "${cluster_name}"

echo "*******************************************************************"
echo "Getting ECR credentials"
ecr_username=$(kubectl get secrets -n formbuilder-repos ecr-credentials -o jsonpath="{.data.ecr_username}" | base64 -d)
ecr_password=$(kubectl get secrets -n formbuilder-repos ecr-credentials -o jsonpath="{.data.ecr_password}" | base64 -d)
echo "*******************************************************************"
echo

echo "*******************************************************************"
echo "Getting secrets from AWS"
export AWS_DEFAULT_REGION=eu-west-2
export AWS_ACCESS_KEY_ID=$(kubectl get secrets -n formbuilder-repos ecr-repo-fb-maintenance-page -o jsonpath='{.data.access_key_id}' | base64 -d)
export AWS_SECRET_ACCESS_KEY=$(kubectl get secrets -n formbuilder-repos ecr-repo-fb-maintenance-page -o jsonpath='{.data.secret_access_key}' | base64 -d)
export ECR_REPO_URL=$(kubectl get secrets -n formbuilder-repos ecr-repo-fb-maintenance-page -o jsonpath='{.data.repo_url}' | base64 -d)
echo "*******************************************************************"
echo

echo "*******************************************************************"
echo 'Logging into AWS ECR'
aws ecr get-login-password --region eu-west-2 | docker login --username ${ecr_username} --password-stdin ${ecr_password}
echo "*******************************************************************"
echo

echo "*******************************************************************"
echo "Maintenance Page App. Building fb-maintenance-page:latest"
docker build -t "${ECR_REPO_URL}:latest" .
echo "*******************************************************************"
echo

echo "*******************************************************************"
echo "Pushing image for fb-maintenance-page:latest"
docker push "${ECR_REPO_URL}:latest"
echo "*******************************************************************"
echo
